# MySQL-Front 5.0  (Build 1.0)

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;


# Host: localhost    Database: covid
# ------------------------------------------------------
# Server version 8.0.19

DROP DATABASE IF EXISTS `covid`;
CREATE DATABASE `covid` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `covid`;

#
# Table structure for table geral2
#

CREATE TABLE `geral2` (
  `codgeral` int NOT NULL AUTO_INCREMENT,
  `IBGE_RES_PR` int DEFAULT NULL,
  `IBGE_ATEND_PR` int DEFAULT NULL,
  `SEXO` varchar(1) DEFAULT NULL,
  `IDADE_ORIGINAL` int DEFAULT NULL,
  `MUN_RESIDENCIA` varchar(255) DEFAULT NULL,
  `MUN_ATENDIMENTO` varchar(255) DEFAULT NULL,
  `LABORATORIO` varchar(255) DEFAULT NULL,
  `DATA_DIAGNOSTICO` date DEFAULT NULL,
  `DATA_CONFIRMACAO_DIVULGACAO` date DEFAULT NULL,
  `DATA_INICIO_SINTOMAS` date DEFAULT NULL,
  `OBITO` varchar(3) DEFAULT NULL,
  `DATA_OBITO` date DEFAULT NULL,
  `DATA_OBITO_DIVULGACAO` date DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `DATA_RECUPERADO_DIVULGACAO` datetime DEFAULT NULL,
  `FONTE_DADO_RECUPERADO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`codgeral`),
  KEY `indx_dtdiag` (`DATA_DIAGNOSTICO`),
  KEY `indx_dataconf` (`DATA_CONFIRMACAO_DIVULGACAO`),
  KEY `indx_datasint` (`DATA_INICIO_SINTOMAS`),
  KEY `indx_dataobito` (`DATA_OBITO`),
  KEY `indx_datarecup` (`DATA_RECUPERADO_DIVULGACAO`),
  KEY `indx_idade` (`IDADE_ORIGINAL`),
  KEY `indx_sexo` (`SEXO`)
) ENGINE=InnoDB AUTO_INCREMENT=438370 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
